POST https://tandafuria.herokuapp.com/users HTTP/1.1
//POST http://localhost:4000/users HTTP/1.1
content-type: application/json

{
  "username": "fab.grignoux@gmail.com",
  "nickname": "Fabien Grignoux",
  "password": "kreposuc666",
  "role": "user"
}

###

POST http://localhost:4000/auth/signin HTTP/1.1
content-type: application/json

{
  "username": "fab.grignoux@gmail.com",
  "password": "kreposuc666"
}
